name: legend-dataflow-scripts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3